// The After Effects emitter (build-order item 6, D6 and the five gate calls
// approved 2026-09-05): the token set as a runnable ExtendScript that creates
// or updates the `TOKENS Motion` layer in the active comp, per the
// CadenceButtonRig mapping. Re-running the script (or running a different
// preset's file) retimes the comp.
//
// Like every emitter here it serializes from stateToExport, so the values
// cannot drift from the other formats. The CONTROL NAMES are the contract
// with the rig: expressions reach control layers by name, so each name below
// must match tools/after-effects/CadenceButtonRig.jsx verbatim (a test reads
// the rig source and asserts exactly that). Two control families ride along
// unread by the rig, per its own complete-document rationale: the spring
// sliders (the rig ships them with the same "(unused)" names) and the Enter /
// Exit point-control pairs this emitter adds (Q2). Deliberately absent: the
// routing dropdowns and Retime Scalar (rig-owned, Q5), ease.linear (corner
// handles, nothing to author), delay.none (implicit zero), and the duration
// scalar (no consumer in AE; same reasoning as the Framer Motion export).
//
// The emitted script is ExtendScript, which is ES3: var-only, no arrow
// functions, no const/let, string concatenation over templates. A test pins
// that too, because a stray modern token would fail silently-in-AE, loudly
// here.

import { stateToExport } from './index.js'

// The control table for one state: [name, type, value] triples in the rig's
// display order. Point values are [x, y] bezier handles; a four-number curve
// splits into P1 (indices 0,1) and P2 (indices 2,3).
export function toAfterEffectsControls(state) {
  const t = stateToExport(state)
  const curve = (label, arr) => [
    [`Ease ${label} P1`, 'point', [arr[0], arr[1]]],
    [`Ease ${label} P2`, 'point', [arr[2], arr[3]]],
  ]
  return [
    ['Duration Fast (ms)', 'slider', t.duration.fast],
    ['Duration Base (ms)', 'slider', t.duration.base],
    ['Duration Slow (ms)', 'slider', t.duration.slow],
    ['Duration Slower (ms)', 'slider', t.duration.slower],
    ['Delay Short (ms)', 'slider', t.delay.short],
    ['Delay Medium (ms)', 'slider', t.delay.medium],
    ['Delay Long (ms)', 'slider', t.delay.long],
    ['Scale Press Subtle', 'slider', t.scale.pressSubtle],
    ['Scale Press Base', 'slider', t.scale.pressBase],
    ['Scale Press Expressive', 'slider', t.scale.pressExpressive],
    ['Scale Lift', 'slider', t.scale.lift],
    ...curve('Standard', t.easing.standard),
    ...curve('Overshoot', t.easing.overshoot),
    // Enter and Exit ride along unread by the bezier rig (Q2), the same
    // posture as the spring sliders below: the layer is a complete Cadence
    // token document, and a rig variant that wants them has somewhere to read.
    ...curve('Enter', t.easing.enter),
    ...curve('Exit', t.easing.exit),
    ['Spring Stiffness (unused)', 'slider', t.spring.stiffness],
    ['Spring Damping (unused)', 'slider', t.spring.damping],
    ['Spring Mass (unused)', 'slider', t.spring.mass],
  ]
}

// One [name, type, value] triple as an ES3 array literal line.
function controlLine([name, type, value]) {
  const v = Array.isArray(value) ? `[${value.join(', ')}]` : String(value)
  return `    ['${name}', '${type}', ${v}]`
}

export function toAfterEffects(state, { label = 'Standard', version = '0.0.0' } = {}) {
  const controls = toAfterEffectsControls(state)
  const table = controls.map(controlLine).join(',\n')

  // The script body is assembled from plain strings (not a tagged template)
  // so the emitter file itself stays modern JS while the OUTPUT stays ES3.
  return `// Cadence motion tokens, ${label} preset, as the TOKENS Motion layer.
//
// Generated by cadence-tokens ${version}. Run in After Effects
// (File > Scripts > Run Script File) with the target comp active.
//
// What it does: finds the layer named 'TOKENS Motion' in the active comp, or
// creates it (a null guide layer, the CadenceButtonRig convention) if absent.
// Each token control is set by name; a missing control is added with its
// type. Nothing is ever deleted, and controls this script does not own (the
// routing dropdowns, Retime Scalar, anything you added) are never touched. A
// control with keyframes is skipped and reported rather than having its keys
// destroyed. Re-running this file, or a different preset's file, retimes the
// comp. That is the argument the whole system makes: the values live in one
// place and the rig reads them.
(function () {
  var LAYER_NAME = 'TOKENS Motion';
  var PRESET = '${label}';

  // [name, type, value] per control. Point values are bezier handles, two
  // numbers, unitless; y is free to pass 1 (that is how overshoot works).
  var CONTROLS = [
${table}
  ];

  var comp = app.project ? app.project.activeItem : null;
  if (!(comp && comp instanceof CompItem)) {
    alert('Cadence tokens: open the target comp first, then run this script.');
    return;
  }

  app.beginUndoGroup('Cadence tokens: ' + PRESET);

  var layer = null;
  for (var i = 1; i <= comp.numLayers; i++) {
    if (comp.layer(i).name === LAYER_NAME) { layer = comp.layer(i); break; }
  }
  var createdLayer = false;
  if (!layer) {
    layer = comp.layers.addNull();
    layer.name = LAYER_NAME;
    // A rig null, not artwork: guide layers never render.
    layer.guideLayer = true;
    createdLayer = true;
  }

  var fx = layer.property('ADBE Effect Parade');
  function findEffect(name) {
    for (var j = 1; j <= fx.numProperties; j++) {
      if (fx.property(j).name === name) { return fx.property(j); }
    }
    return null;
  }

  var setCount = 0;
  var added = [];
  var skipped = [];
  for (var k = 0; k < CONTROLS.length; k++) {
    var name = CONTROLS[k][0];
    var type = CONTROLS[k][1];
    var value = CONTROLS[k][2];
    var effect = findEffect(name);
    if (!effect) {
      effect = fx.addProperty(type === 'point' ? 'ADBE Point Control' : 'ADBE Slider Control');
      effect.name = name;
      added.push(name);
    }
    var prop = effect.property(1);
    if (prop.numKeys > 0) {
      // setValue cannot write a keyframed property, and destroying keys is
      // not this script's call to make.
      skipped.push(name + ' (keyframed)');
      continue;
    }
    try {
      prop.setValue(value);
      setCount += 1;
    } catch (err) {
      // Most likely a name collision with a control of another type.
      skipped.push(name + ' (' + err.toString() + ')');
    }
  }

  app.endUndoGroup();

  var lines = ['Cadence tokens: ' + PRESET];
  lines.push((createdLayer ? 'Created ' : 'Updated ') + "'" + LAYER_NAME + "' in '" + comp.name + "'.");
  lines.push(setCount + ' values set, ' + added.length + ' controls added.');
  if (skipped.length > 0) {
    lines.push('Skipped: ' + skipped.join(', '));
  }
  alert(lines.join('\\n'));
})();
`
}
