// The export format table: everything Token Lab knows about the seven files it
// can write, in one place (six at the modal's launch; Figma joined 2026-09-15).
//
// Before the export modal (2026-09-15) this knowledge was spread across the
// tool bar section: a four-button toggle, an `exportText()` chain of ifs, a
// filename map, a wire-name map for the counter, and a second copy of the
// stringifier list in the capture rig with the highlight language added. Six
// formats made that arrangement worse in every place at once, so the table is
// the single source and every surface (the modal, the tool bar, the rig, the
// tests) reads it.
//
// Fields, per format:
//   key          the UI's internal id, stable across renames of anything else
//   label        the name a reader sees in the format list
//   description  one sentence saying what the file is for and who reads it
//   filename     what the download is called; each carries its conventional
//                extension so the file opens as its own type
//   mime         the Blob type, matched to the extension
//   language     the Prism grammar the preview highlights with
//   wire         the name the /api/event counter records. The counter speaks
//                the endpoint's contract ('json', 'framer-motion') rather than
//                the UI's keys ('flat', 'fm') so the metrics report reads
//                without a decoder ring. `exportFormats.test.js` pins this
//                column to the Worker's allowlist by reading the Worker source.
//   reimports    whether importTokens can read the file back. DTCG and flat
//                are interchange formats; the other four are destinations.
//   carriesDeviations
//                whether the off-system appendix rides this file (see below).
//                The modal reads it to say so beside the file rather than
//                letting a reader assume a deviation travelled when it did not.
//   stringify    (state, opts) -> text. All six serialize from the package's
//                single stateToExport object, so the files cannot drift apart.
//
// Off-system deviations (a demo running a literal in place of a token) ride the
// four token-document formats as an appendix in each one's idiom. After Effects
// and Flow do not carry them: the AE script writes a control layer and the Flow
// library is a curve set, and neither has a place for "this one demo declined
// the token". The table says so per format rather than the modal guessing.
import {
  toDtcgJson,
  toFlatJson,
  toCssVars,
  toFramerMotion,
  toAfterEffects,
  toFlow,
  toFigmaJson,
} from 'cadence-tokens'
// The package version, for the After Effects script header ("Generated by
// cadence-tokens 2.0.0"). Read from the manifest rather than restated here so
// a version bump in the package cannot leave the shipped script claiming an
// older one. A relative import because the package's exports map exposes only
// its entry and two dist files, and this is the one consumer of the manifest.
import tokensPackage from '../../../packages/tokens/package.json'

export const TOKENS_PACKAGE_VERSION = tokensPackage.version

// The label a state export is headed with. The active preset's name when the
// set matches one, and "Custom" when it does not: a set the user has edited is
// no longer that preset, and a script headed "Standard preset" that retimes a
// comp to something else would misdescribe itself. Same rule as the audit's
// heading, which uses null for the same case; the AE header needs a word.
export function exportLabel(presetLabel) {
  return presetLabel ?? 'Custom'
}

export const EXPORT_FORMATS = [
  {
    key: 'dtcg',
    label: 'DTCG',
    description: 'The W3C Design Tokens format. Style Dictionary and Tokens Studio read it, and Token Lab reads it back.',
    filename: 'cadence.tokens.json',
    mime: 'application/json',
    language: 'json',
    wire: 'dtcg',
    reimports: true,
    carriesDeviations: true,
    stringify: (state, { deviations = [] } = {}) => toDtcgJson(state, { deviations }),
  },
  {
    key: 'flat',
    label: 'Flat JSON',
    description: 'One flat object whose keys mirror the CSS variable names. Token Lab reads it back.',
    filename: 'cadence-tokens.json',
    mime: 'application/json',
    language: 'json',
    wire: 'json',
    reimports: true,
    carriesDeviations: true,
    stringify: (state, { deviations = [] } = {}) => toFlatJson(state, { deviations }),
  },
  {
    key: 'css',
    label: 'CSS',
    description: 'A drop-in :root block of custom properties, with the reduced-motion resolution in its own media block.',
    filename: 'cadence.tokens.css',
    mime: 'text/css',
    language: 'css',
    wire: 'css',
    reimports: false,
    carriesDeviations: true,
    stringify: (state, { deviations = [] } = {}) => toCssVars(state, { deviations }),
  },
  {
    key: 'fm',
    label: 'Framer Motion',
    description: 'A JavaScript module of ready transition values in seconds, with the spring as a native config.',
    filename: 'cadence.motion.js',
    mime: 'text/javascript',
    language: 'jsx',
    wire: 'framer-motion',
    reimports: false,
    carriesDeviations: true,
    stringify: (state, { deviations = [] } = {}) => toFramerMotion(state, { deviations }),
  },
  {
    key: 'ae',
    label: 'After Effects',
    description: 'An ExtendScript that writes these values onto the TOKENS Motion layer of the active comp. Run it again to retime.',
    filename: 'cadence.tokens.jsx',
    mime: 'text/javascript',
    language: 'jsx',
    wire: 'after-effects',
    reimports: false,
    carriesDeviations: false,
    stringify: (state, { presetLabel = null } = {}) =>
      toAfterEffects(state, { label: exportLabel(presetLabel), version: TOKENS_PACKAGE_VERSION }),
  },
  {
    key: 'flow',
    label: 'Flow',
    description: 'The curve set as a Flow library. Import it once in the panel, then apply the named curves in After Effects.',
    filename: 'cadence.flow.txt',
    mime: 'text/plain',
    language: 'json',
    wire: 'flow',
    reimports: false,
    carriesDeviations: false,
    stringify: (state) => toFlow(state),
  },
  {
    key: 'figma',
    label: 'Figma',
    description: 'A variables document: one collection, this set as a mode, with native TIMING and EASING types a plugin or the Figma MCP maps one to one.',
    filename: 'cadence.figma.json',
    mime: 'application/json',
    language: 'json',
    wire: 'figma',
    reimports: false,
    carriesDeviations: false,
    stringify: (state, { presetLabel = null } = {}) => toFigmaJson(state, { presetLabel }),
  },
]

export const EXPORT_FORMAT_KEYS = EXPORT_FORMATS.map(f => f.key)

export function exportFormat(key) {
  const format = EXPORT_FORMATS.find(f => f.key === key)
  if (!format) throw new Error(`Unknown export format: ${key}`)
  return format
}

// The file for one format and one state: what the download writes and what
// the counter records. Export and Copy both call this rather than holding the
// text in state, so the text is always the state at the moment of the click.
export function exportFile(key, state, { deviations = [], presetLabel = null } = {}) {
  const format = exportFormat(key)
  return {
    filename: format.filename,
    mime: format.mime,
    wire: format.wire,
    text: format.stringify(state, { deviations, presetLabel }),
  }
}
